$ \[
\begin{bmatrix}
2 & 4 \\
6 & 2
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix}
=
\begin{bmatrix}
5 \\
7
\end{bmatrix}
\]

\[
A =
\begin{bmatrix}
2 & 4 \\
6 & 2
\end{bmatrix},
\quad
X =
\begin{bmatrix}
x \\
y
\end{bmatrix},
\quad
B =
\begin{bmatrix}
5 \\
7
\end{bmatrix}
\]

\[
AX = B \quad \Rightarrow \quad X = A^{-1}B
\]

\[
A^{-1} =
\frac{1}{(2)(2) - (6)(4)}
\begin{bmatrix}
2 & -4 \\
-6 & 2
\end{bmatrix}
=
\frac{1}{-20}
\begin{bmatrix}
2 & -4 \\
-6 & 2
\end{bmatrix}
\]

\[
X =
\frac{1}{-20}
\begin{bmatrix}
2 & -4 \\
-6 & 2
\end{bmatrix}
\begin{bmatrix}
5 \\
7
\end{bmatrix}
=
\frac{1}{-20}
\begin{bmatrix}
2\cdot 5 + (-4)\cdot 7 \\
-6\cdot 5 + 2\cdot 7
\end{bmatrix}
=
\frac{1}{-20}
\begin{bmatrix}
-18 \\
-16
\end{bmatrix}
\]

\[
X =
\begin{bmatrix}
0.9 \\
0.8
\end{bmatrix}
\quad \Rightarrow \quad
x = 0.9,\; y = 0.8
\]
 $

In [1]:
import numpy as np

# 계수 행렬 A
A = np.array([[2, 4],
              [6, 2]])

# 상수 벡터 B
B = np.array([5, 7])

# 해 구하기 (X = A^{-1}B)
X = np.linalg.solve(A, B)

print("해:", X)
print(f"x = {X[0]}, y = {X[1]}")


해: [0.9 0.8]
x = 0.9, y = 0.8


\[
\text{주어진 연립방정식:}
\]

\[
\begin{cases}
2x + 4y = 5 \\
6x + 2y = 7
\end{cases}
\]

\[
\text{이를 행렬 형태로 쓰면: }
\quad
\begin{bmatrix}
2 & 4 \\
6 & 2
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix}
=
\begin{bmatrix}
5 \\
7
\end{bmatrix}
\]

\[
AX = B, \quad X = A^{-1}B
\]

\[
A =
\begin{bmatrix}
2 & 4 \\
6 & 2
\end{bmatrix},
\quad
B =
\begin{bmatrix}
5 \\
7
\end{bmatrix}
\]

\[
\det(A) = (2)(2) - (6)(4) = 4 - 24 = -20
\]

\[
A^{-1} =
\frac{1}{\det(A)}
\begin{bmatrix}
2 & -4 \\
-6 & 2
\end{bmatrix}
=
\frac{1}{-20}
\begin{bmatrix}
2 & -4 \\
-6 & 2
\end{bmatrix}
\]

\[
X = A^{-1}B =
\frac{1}{-20}
\begin{bmatrix}
2 & -4 \\
-6 & 2
\end{bmatrix}
\begin{bmatrix}
5 \\
7
\end{bmatrix}
\]

\[
=
\frac{1}{-20}
\begin{bmatrix}
2\cdot 5 + (-4)\cdot 7 \\
-6\cdot 5 + 2\cdot 7
\end{bmatrix}
=
\frac{1}{-20}
\begin{bmatrix}
-18 \\
-16
\end{bmatrix}
\]

\[
X =
\begin{bmatrix}
0.9 \\
0.8
\end{bmatrix}
\quad \Rightarrow \quad
x = 0.9,\; y = 0.8
\]


In [2]:
x=0.9
y=0.8
2*x+4*y - 5 <0.001

True

In [3]:
6*x+2*y - 7 < 0.001

True

In [4]:
import numpy as np

In [5]:
x1=np.array( [ [1,3,5],
     [3 ,4, 6],
     [-1,3,5]])
x1

array([[ 1,  3,  5],
       [ 3,  4,  6],
       [-1,  3,  5]])

In [6]:
xy= np.linalg.inv(x1)
result = np.dot(x1,xy)
result

array([[ 1.00000000e+00, -6.66133815e-16, -6.66133815e-16],
       [ 0.00000000e+00,  1.00000000e+00, -4.44089210e-16],
       [-1.77635684e-15,  1.11022302e-15,  1.00000000e+00]])

In [7]:
# 불필요한 소수점 오차를 없애기 위해 반올림
I_clean = np.round(result, decimals=6)  # 소수점 6자리까지 반올림
I_clean

array([[ 1., -0., -0.],
       [ 0.,  1., -0.],
       [-0.,  0.,  1.]])

In [8]:
y1 = ( [
        [1,3,5],
        [3,4,6],
        [-1,3,5]]
     )
b=np.array([11,3,11])
yy = np.linalg.inv(y1)
result = np.dot(yy,y1)
result

array([[ 1.00000000e+00, -5.55111512e-16, -1.11022302e-16],
       [-1.33226763e-15,  1.00000000e+00, -3.99680289e-15],
       [ 6.66133815e-16,  6.66133815e-16,  1.00000000e+00]])

In [9]:
solution = np.dot(yy,b)
np.round(solution,decimals=6)

array([  0. , -25.5,  17.5])

In [10]:
x11 = 0.
x12 = -25.5
x13 = 17.5

In [11]:
re1 = -1*x11 + 2*x12 + 1*x13 -3 < 0.1
re2 = 2*x11 - 3*x12 + 9*x13 - 11 < 0.1
re3 = 3*x11 + 4*x12 + 6*x13 - 11 < 0.0001
re1,re2,re3

(True, False, True)

In [12]:
re1 = 1*x11 + 3*x12 + 5*x13 -11 < 0.1
re2 = 3*x11 + 4*x12 + 6*x13 -3 < 0.1
re3 = -1*x11 + 3*x12 + 5*x13 - 11 < 0.1
re1,re2,re3

(True, True, True)

$ f(x) = 3x^2 + 7x + 6 $

$ \text{적분 구간: } \int_{2}^{5} f(x)\,dx $

$ 
F(x) = \int f(x)\,dx 
= x^3 + \tfrac{7}{2}x^2 + 6x
 $

$ \int_{2}^{5} f(x)\,dx
= \Bigl[ x^3 + \tfrac{7}{2}x^2 + 6x \Bigr]_{2}^{5}
= \Bigl(125 + \tfrac{7}{2}\cdot 25 + 30 \Bigr) - \Bigl(8 + \tfrac{7}{2}\cdot 4 + 12 \Bigr)   $

$  = 188.5 - (-19) = \tfrac{417}{2} = 208.5 $

$  \therefore \quad \text{정확한 면적은 } 208.5   $

In [13]:
import matplotlib.pyplot as plt

# ---- SymPy 적분 ----
x = sp.Symbol('x', real=True)
f = 3*x**2 + 7*x + 6
a, b = 2, 5

F = sp.integrate(f, x)                 # 부정적분
area_exact = sp.integrate(f, (x, a, b))  # [2,5] 구간 면적

print("부정적분 F(x) =", F)
print(f"정확한 면적 ∫_{{{a}}}^{{{b}}} f(x) dx =", area_exact)

# ---- 반복문으로 여러 개수의 직사각형 ----
rect_counts = [2, 3, 7, 10, 100]

xs = np.linspace(a, b, 400)
f_np = sp.lambdify(x, f, 'numpy')

# subplot을 2행 3열로 준비 (최대 6개까지)
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
axes = axes.flatten()

for idx, N in enumerate(rect_counts):
    dx = (b - a) / N
    sample_x = np.linspace(a + dx/2, b - dx/2, N)  # midpoint rule
    heights = f_np(sample_x)
    riemann_sum = np.sum(heights * dx)

    ax = axes[idx]
    ax.plot(xs, f_np(xs), 'orange', label='f(x) = 3x^2+7x+6')

    # 직사각형 그리기
    for xi, hi in zip(sample_x, heights):
        ax.bar(xi, hi, width=dx, alpha=0.3, edgecolor='black')

    ax.axvline(a, linestyle='--', alpha=0.6)
    ax.axvline(b, linestyle='--', alpha=0.6)

    ax.set_title(f"N={N} 직사각형\n"
                 f"리만합 ≈ {riemann_sum:.4f}, 정확한 면적 = {float(area_exact):.4f}")
    ax.set_xlabel('x')
    ax.set_ylabel('f(x)')
    ax.legend()

plt.tight_layout()
plt.show()

NameError: name 'sp' is not defined

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# 변수 선언
x = sp.Symbol('x', real=True)

# 함수 정의
f = sp.sin(2*x)*sp.cos(3*x) + x**7 + sp.cos(8*x)

# 미분
f_prime = sp.diff(f, x)

print("원래 함수 f(x) =", f)
print("도함수 f'(x) =", f_prime)

# numpy 변환
f_np = sp.lambdify(x, f, 'numpy')
f_prime_np = sp.lambdify(x, f_prime, 'numpy')

# x 범위
xs = np.linspace(-2, 2, 400)   # 필요시 범위 조정
ys = f_np(xs)
ys_prime = f_prime_np(xs)

# 그래프
plt.figure(figsize=(10, 6))
plt.plot(xs, ys, label="f(x)", color="blue")
plt.plot(xs, ys_prime, label="f'(x)", color="red", linestyle="--")

plt.title("함수와 도함수 그래프")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.show()

<img src="images/a.PNG"/>